models/product.py
from sqlalchemy import *
from extentions import db


class Product(db.Model):
    __tablename__ = "products"
    id = Column(Integer, primary_key=True)
    name = Column(String, unique=True, nullable=False, index=True)
    description = Column(String, nullable=False, index=True)
    price = Column(Integer, nullable=False, index=True)
    active = Column(Integer, nullable=False, index=True)

blueprints/general.py
from flask import Blueprint, render_template, request
from sqlalchemy.sql.expression import func

from models.product import Product

app = Blueprint("general", __name__)


@app.route('/')
def main():
    search = request.args.get('search', None)

    products = Product.query.filter(Product.active == 1)

    if search != None:
        products = products.filter(Product.name.like(f'%{search}%'))

    products = products.order_by(func.random()).all()

    return render_template('main.html', products=products, search=search)


@app.route('/product/<int:id>/<name>')
def product(id, name):
    product = Product.query.filter(Product.id == id).filter(Product.name == name).filter(
        Product.active == 1).first_or_404()

    another_products = Product.query.filter(Product.active == 1).filter(
        Product.name.like(f'%{product.name[0:5]}%')).order_by(func.random()).limit(3).all()

    return render_template('product.html', product=product, another_products=another_products)


@app.route('/about')
def about():
    return render_template('about.html')

templates/part/header.html
<header>
    <section>
        <a href="/">
            <img src="{{ url_for('static',filename = 'image/logo.png') }}" alt="online tech">
        </a>
        <div id="header-menu">
            <span id="header-menu-close-btn" onclick="javascript:change_header_menu(false)">X</span>

            {% if  request.endpoint.startswith("admin") %}
                <a class="header-link" href="/admin/dashboard">پنل مدیریت</a>
                <a class="header-link" href="/admin/dashboard/products">صفحه محصولات</a>
            {% else %}
                <form action="/" method="get">
                    <input type="search" name="search" value="{{ search if search != None }}" placeholder="جستجو...">
                </form>
                <a class="header-link" href="/cart">سبدخرید</a>
                {% if current_user.is_authenticated %}
                    <a class="header-link" href="/user/dashboard">پنل کاربری</a>
                {% else %}
                    <a class="header-link" href="/user/login">ورود/ثبت نام</a>
                {% endif %}
                <a class="header-link" href="/about">درباره ما</a>
            {% endif %}
        </div>

        <img src="{{ url_for('static',filename = 'theme-image/menu.png') }}" id="header-menu-btn"
             onclick="javascript:change_header_menu(true)">
    </section>
</header>

templates/part/product.html
<div class="product-box">
    <a style="all:unset;cursor: pointer;" href="{{ url_for('general.product', id=p.id, name=p.name) }}">
        <section>
            <img src="{{ url_for('static', filename='cover/'+p.id|string+'.jpg') }}">
            <span class="tag green" style="margin-right: 5px;"><img
                    src="{{ url_for('static',filename="theme-image/delivery.png") }}">{{ myconfig.feature1 }}</span>
            <span class="tag blue"><img
                    src="{{ url_for('static',filename="theme-image/done.png") }}">{{ myconfig.feature2 }}</span>


            <h3>{{ p.name }}</h3>
            <p>{{ p.description|truncate(250) }}</p>

            <span class="price" style="float: left;padding-left: 10px;">{{ p.price }}</span>
        </section>
    </a>

    <a class="add-to-cart-btn icon" href="/add-to-cart?id={{ p.id }}"> افزودن به <img
            src="{{ url_for('static',filename="theme-image/cart.png") }}"></a>

</div>