models/cart.py
from sqlalchemy import *
from sqlalchemy.orm import backref

from extentions import db


class Cart(db.Model):
    __tablename__ = "carts"
    id = Column(Integer, primary_key=True)
    status = Column(String, default='pending')
    user_id = Column(Integer, ForeignKey('users.id'), nullable=False)
    user = db.relationship("User", backref=backref('carts', lazy='dynamic'))

    def total_price(self):
        total = 0
        for item in self.cart_items:
            t = item.price * item.quantity
            total += t
        return total

    def get_status_persian(self):
        if self.status == 'pending':
            return "در انتظار پرداخت (سبد خرید)"

        if self.status == "paid":
            return "پرداخت شده"

        if self.status == "sent":
            return "ارسال شده"

        if self.status == "rejected":
            return "رد شده"

models/user.py
from sqlalchemy import *
from extentions import db,get_current_time
from flask_login import UserMixin

class User(db.Model, UserMixin):
    __tablename__ = "users"
    id = Column(Integer, primary_key=True)
    username = Column(String, unique=True, nullable=False, index=True)
    password = Column(String, nullable=False, index=True)
    phone = Column(String(11), nullable=False, index=True)
    address = Column(String, nullable=False, index=True)
    date_created = Column(String(15), default=get_current_time)

blueprints/user.py
from flask import Blueprint, render_template, request, redirect, url_for, flash
from flask_login import login_user, login_required, current_user,logout_user
from passlib.hash import sha256_crypt
from extentions import db
from models.Payment import Payment
from models.cart import Cart
from models.cart_item import CartItem
from models.product import Product
from models.user import User
import requests
import config

app = Blueprint("user", __name__)


@app.route('/user/login', methods=['GET', 'POST'])
def login():
    if request.method == 'GET':
        if current_user.is_authenticated:
            return redirect(url_for('user.dashboard'))
        return render_template('user/login.html')
    else:
        register = request.form.get('register', None)
        username = request.form.get('username', None)
        password = request.form.get('password', None)
        phone = request.form.get('phone', None)
        address = request.form.get('address', None)

        if register != None:
            user = User.query.filter(User.username == username).first()
            if user != None:
                flash('نام کاربری دیگری انتخاب کنید')
                return redirect(url_for('user.login'))

            user = User(username=username, password=sha256_crypt.encrypt(password), phone=phone, address=address)
            db.session.add(user)
            db.session.commit()
            login_user(user)

            return redirect(url_for('user.dashboard'))

        else:
            user = User.query.filter(User.username == username).first()
            if user == None:
                flash('نام کابربر یا رمز اشتباه است')
                return redirect(url_for('user.login'))

            if sha256_crypt.verify(password, user.password):
                login_user(user)
                return redirect(url_for('user.dashboard'))
            else:
                flash('نام کابربر یا رمز اشتباه است')
                return redirect(url_for('user.login'))


@app.route('/add-to-cart', methods=['GET'])
@login_required
def add_to_cart():
    id = request.args.get('id')
    product = Product.query.filter(Product.id == id).first_or_404()

    cart = current_user.carts.filter(Cart.status == 'pending').first()
    if cart == None:
        cart = Cart()
        current_user.carts.append(cart)
        db.session.add(cart)

    cart_item = cart.cart_items.filter(CartItem.product == product).first()
    if cart_item == None:
        item = CartItem(quantity=1)
        item.price = product.price
        item.cart = cart
        item.product = product
        db.session.add(item)
    else:
        cart_item.quantity += 1

    db.session.commit()

    return redirect(url_for('user.cart'))


@app.route('/remove-from-cart', methods=['GET'])
@login_required
def remove_from_cart():
    id = request.args.get('id')
    cart_item = CartItem.query.filter(CartItem.id == id).first_or_404()
    if cart_item.quantity > 1:
        cart_item.quantity -= 1
    else:
        db.session.delete(cart_item)

    db.session.commit()
    return redirect(url_for('user.cart'))


@app.route('/cart', methods=['GET'])
@login_required
def cart():
    cart = current_user.carts.filter(Cart.status == "pending").first()
    return render_template('user/cart.html', cart=cart)


@app.route('/payment', methods=['GET'])
@login_required
def payment():
    cart = current_user.carts.filter(Cart.status == 'pending').first()

    r = requests.post(config.PAYMENT_FIRST_REQUEST_URL,
                      data={
                          'api': config.PAYMENT_MERCHANT,
                          'amount': cart.total_price(),
                          'callback': config.PAYMENT_CALLBACK
                      })
    token = r.json()['result']['token']
    url = r.json()['result']['url']

    pay = Payment(price=cart.total_price(), token=token)
    pay.cart = cart
    db.session.add(pay)
    db.session.commit()

    return redirect(url)


@app.route('/verify', methods=['GET'])
@login_required
def verify():
    token = request.args.get('token')
    pay = Payment.query.filter(Payment.token == token).first_or_404()
    r = requests.post(config.PAYMENT_VERIFY_REQUEST_URL,
                      data={
                          'api': 'sandbox',
                          'amount': pay.price,
                          'token': token
                      })

    pay_status = bool(r.json()['success'])
    if pay_status:
        transaction_id = r.json()['result']['transaction_id']
        refid = r.json()['result']['refid']
        card_pan = r.json()['result']['card_pan']

        pay.card_pan = card_pan
        pay.transaction_id = transaction_id
        pay.refid = refid
        pay.status = 'success'
        pay.cart.status = 'paid'
        flash("پرداخت موفق آمیز بود")
    else:
        flash("پرداخت با خطا مواجه شد")
        pay.status = 'failed'

    db.session.commit()

    return redirect(url_for('user.dashboard'))


@app.route('/user/dashboard', methods=['GET', 'POST'])
@login_required
def dashboard():
    if request.method == "GET":
        return render_template('user/dashboard.html')
    else:
        username = request.form.get('username', None)
        password = request.form.get('password', None)
        phone = request.form.get('phone', None)
        address = request.form.get('address', None)

        if current_user.username != username:
            user = User.query.filter(User.username == username).first()
            if user != None:
                flash('نام کاربری از قبل انتخاب شده است')
                return redirect(url_for('user.dashboard'))
            else:
                current_user.username = username

        if password != None:
            current_user.password = sha256_crypt.encrypt(password)

        current_user.address = address
        current_user.phone = phone
        db.session.commit()

        flash('تغییرات با موفقیت ثبت شد')
        return redirect(url_for('user.dashboard'))


@app.route('/user/logout', methods=['GET'])
@login_required
def logout():
    logout_user()
    flash("با موفقیت خارج شدید")
    return redirect('/')



@app.route('/user/dashboard/order/<id>', methods=['GET'])
@login_required
def order(id):
    cart = current_user.carts.filter(Cart.id == id).first_or_404()
    return render_template('user/order.html', cart=cart)

templates/user/cart.html
{% extends 'base.html' %}
{% block haeder %}
    <title>سبدخرید</title>
{% endblock %}
{% block body %}

    {% include 'part/header.html' %}


    <section class="simple-box cart">
        <h1>سبدخرید</h1>
        {% if cart != None and cart.cart_items|list|length > 0 %}
            <table class="cart">
                <tr>
                    <th>محصول</th>
                    <th>قیمت</th>
                    <th>تعداد</th>
                </tr>
                {% for cart_item in cart.cart_items %}
                    <tr>
                        <td>{{ cart_item.product.name }}</td>
                        <td class="price">{{ cart_item.price }}</td>
                        <td>
                            <div style="display: flex;justify-content: center;align-items: center;">
                            <a class="cartitem-btn"
                               href="/remove-from-cart?id={{ cart_item.id }}">-</a>{{ cart_item.quantity }}<a
                                class="cartitem-btn"
                                href="/add-to-cart?id={{ cart_item.product.id }}">+</a>
                            </div>
                        </td>
                    </tr>
                {% endfor %}

                <tr>
                    <td colspan="3" style="text-align: left;">قیمت کل : <span class="price">{{ cart.total_price() }}</span></td>
                </tr>
            </table>


            <a class="pay-btn icon" href="/payment"> پرداخت آنلاین <img
                    src="{{ url_for('static',filename="theme-image/wallet.png") }}"></a>


        {% else %}
            <i style="display: block;text-align: center;">سبد خرید خالی است</i>
        {% endif %}

    </section>


{% endblock %}

templates/user/dashboard.html
{% extends 'base.html' %}
{% block haeder %}
    <title>پنل کاربری</title>
{% endblock %}
{% block body %}

    {% include 'part/header.html' %}

    <section class="simple-box cart" style="max-width: 376px">
        <h1>سفارشات</h1>
        {% if current_user.carts|selectattr('status','!=','pending')|list|length > 0 %}
            <table class="cart">
                <tr>
                    <th>شماره سفارش</th>
                    <th>وضعیت</th>
                    <th>مشاهده</th>
                </tr>
                {% for cart in current_user.carts|selectattr('status','!=','pending') %}
                    <tr>
                        <td>{{ cart.id }}</td>
                        <td>{{ cart.get_status_persian() }}</td>
                        <td><a href="{{ url_for('user.order', id=cart.id) }}">جزئیات</a></td>
                    </tr>

                {% endfor %}
            </table>
        {% else %}
            <i style="display: block;text-align: center;">سفارشی وجود ندارد</i>
        {% endif %}

    </section>

    <section class="simple-box" style="max-width: 376px">
        <h1>ویرایش اطلاعات</h1>

        <form action="#" method="post">
            <input type="hidden" name="csrf_token" value="{{ csrf_token() }}">
            <input type="text" name="username" value="{{ current_user.username }}" placeholder="نام کاربری">
            <input type="password" name="password" placeholder="رمز عبور جدید">
            <input type="number" name="phone" value="{{ current_user.phone }}" placeholder="شماره موبایل">
            <textarea name="address" placeholder="آدرس دقیق پستی">{{ current_user.address }}</textarea>
            <input type="submit" value="ثبت تغییرات">
        </form>
    </section>

    <div style="text-align: center;margin-top: 20px;">
        <a href="/user/logout" class="red-btn">خروج از حساب کاربری</a>
    </div>



{% endblock %}

templates/user/login.html
{% extends 'base.html' %}
{% block haeder %}
    <title>ورود/ثبت نام</title>
{% endblock %}
{% block body %}

    {% include 'part/header.html' %}


    <section class="simple-box" style="max-width: 290px;">

        <div id="login-box">
            <h1>ورود</h1>
            <form action="#" method="post">
                <input type="hidden" name="csrf_token" value="{{ csrf_token() }}">
                <input type="text" name="username" placeholder="نام کاربری">
                <input type="password" name="password" placeholder="رمز عبور">
                <input type="submit" value="ورود">
            </form>
            <span style="cursor: pointer;" onclick="javascript:show_register()">ثبت نام نکرده اید؟</span>

        </div>
        <div id="register-box">
            <h1>ثبت نام</h1>
            <form action="#" method="post">
                <input type="hidden" name="csrf_token" value="{{ csrf_token() }}">
                <input type="hidden" name="register" value="1">
                <input type="text" name="username" placeholder="نام کاربری">
                <input type="password" name="password" placeholder="رمز عبور">
                <input type="number" name="phone" placeholder="شماره موبایل">
                <textarea name="address" placeholder="آدرس دقیق پستی"></textarea>
                <input type="submit" value="ثبت نام">
            </form>
            <span  style="cursor: pointer;" onclick="javascript:show_login()">قبلا ثبت نام کرده اید؟</span>

        </div>
    </section>

    <script>
        const register_box = document.getElementById('register-box')
        const login_box = document.getElementById('login-box')

        const show_register = () => {
            register_box.style.display = "block"
            login_box.style.display = "none"
        }

        const show_login = () => {
            login_box.style.display = "block"
            register_box.style.display = "none"
        }
    </script>
{% endblock %}

templates/user/order.html
{% extends 'base.html' %}
{% block haeder %}
    <title>ُسفارش شماره {{ cart.id }}</title>
{% endblock %}
{% block body %}

    {% include 'part/header.html' %}

    <section class="simple-box cart">
        <h1>سفارش شماره {{ cart.id }} - {{ cart.get_status_persian() }}</h1>
        <table class="cart" style="margin-top: 30px">
            <tr>
                <th>شماره محصول</th>
                <th>نام محصول</th>
                <th>قیمت</th>
                <th>تعداد</th>
            </tr>
            {% for item in cart.cart_items %}
                <tr>
                    <td>{{ item.product.id }}</td>
                    <td>{{ item.product.name }}</td>
                    <td class="price">{{ item.price }}</td>
                    <td>{{ item.quantity }}</td>
                </tr>
            {% endfor %}

            <tr>
                <td colspan="3" style="text-align: left" class="price">{{ cart.total_price() }}</td>
            </tr>

        </table>


    <table class="cart" style="margin-top: 30px">
        <tr>
            <th>وضعیت</th>
            <th>مبلغ</th>
            <th>شماره پیگیری</th>
            <th>شماره تراکنش</th>
            <th>شماره کارت</th>
        </tr>

        {% for pay in cart.payments %}
            <tr>
            <td>{{ pay.get_status_persian() }}</td>
            <td class="price">{{ pay.price }}</td>
            <td>{{ pay.refid }}</td>
            <td>{{ pay.transaction_id }}</td>
            <td>{{ pay.card_pan }}</td>
            </tr>
        {% endfor %}
    </table>


    </section>


{% endblock %}